### ISSUE TITLE
JSON Schema version

### ISSUE THREAD

**Issue by char0n** [apiture/openapi-down-convert#24]
Hi,

The main README file of this repo references the JSON Schema version as follows:

> OAS 3.0 uses an earlier JSON Schema version (Draft 7)

This is actually incorrect as the latest OpenAPI 3.0 (OpenAPI 3.0.3) explicitly states that the version of JSON Schema is: [JSON Schema Specification Wright Draft 00](https://tools.ietf.org/html/draft-wright-json-schema-00#section-4.2).

`Wright Draft 00` is actually the `Draft 5` which is technically the `Draft 4` with editorial changes and clarifications.

**Comment by arosenb2** [comment]
This is correct - see [official documentation](https://spec.openapis.org/oas/v3.0.3#data-types).

Good catch @char0n!

**Comment by DavidBiesack** [comment]
fixed in #27 and #27, released as 0.13.1
