### ISSUE TITLE
openIdConnect conversion failing

### ISSUE THREAD

**Issue by arosenb2** [apiture/openapi-down-convert#26]
[converter.ts L392](https://github.com/apiture/openapi-down-convert/blob/main/src/converter.ts#L392) fails on operations that don't have a `security` array.

Either the `sec` variable should null coalesce to `[]` or a check should be put in before chaining `forEach` (`sec?.forEach`).

**Comment by DavidBiesack** [comment]
fixed in #27 and #27, released as 0.13.1
