### ISSUE TITLE
Why is the conversion of OpenIdConnect to oAuth enabled by default?

### ISSUE THREAD

**Issue by MikeRalphson** [apiture/openapi-down-convert#3]
`SecurityScheme`s of type `openIdConnect` are supported in OpenAPI 3.0.x. I can only guess that this is to address limitations in code-gen tooling?

**Comment by DavidBiesack** [comment]
fixed in 0.8.0 -- this conversion is now optional and enabled with the `--oidc-to-oauth2` option or the `--scopes` option.
